#### Packages and folderPath ####

# install.packages("protr")
#install.packages("devtools", dependencies = TRUE)    
#devtools::has_devel()
#devtools::install_github('alanarnholt/BSDA')

library(seqinr)
library(muscle)
library(rentrez)
library(protr)
library(stringr)
library(BSDA)

folderPath <- "/Users/tatemclallen/Desktop/BIOL327/FinalProject/Rresults"

#### end ####



#### Get all sequences from uniprot  ####

seq1 <- getUniProt("A0A222GCN4")
seq1 <- seq1[[1]]
seq1 <- AAStringSet(seq1)
names(seq1) <- "C_beringensis"


seq2 <- getUniProt("A0A1C7DJ11")
seq2 <- seq2[[1]]
seq2 <- AAStringSet(seq2)
names(seq2) <- "P_antarcticus"


seq3 <- getUniProt("Q12YD3")
seq3 <- seq3[[1]]
seq3 <- AAStringSet(seq3)
names(seq3) <- "M_burtonii"

seq4 <- getUniProt("A0A1C7DMD0")
seq4 <- seq4[[1]]
seq4 <- AAStringSet(seq4)
names(seq4) <- "P_halocryophilus"

seq5 <- getUniProt("P00582")
seq5 <- seq5[[1]]
seq5 <- AAStringSet(seq5)
names(seq5) <- "E_coli"

seq6 <- getUniProt("A0A1W1V576")
seq6 <- seq6[[1]]
seq6 <- AAStringSet(seq6)
names(seq6) <- "D_thiosulfatigenes"

seq7 <- getUniProt("A0A5S9C4G5")
seq7 <- seq7[[1]]
seq7 <- AAStringSet(seq7)
names(seq7) <- "S_aureus"

seq8 <- getUniProt("A0A1W1UFF2")
seq8 <- seq8[[1]]
seq8 <- AAStringSet(seq8)
names(seq8) <- "P_asaccharolyticus"


seq9 <- getUniProt("P19821")
seq9 <- seq9[[1]]
seq9 <- AAStringSet(seq9)
names(seq9) <- "T_aquaticus"

seq10 <- getUniProt("P52026")
seq10 <- seq10[[1]]
seq10 <- AAStringSet(seq10)
names(seq10) <- "G_stearothermophilus"


seq11 <- getUniProt("D9TK80")
seq11 <- seq11[[1]]
seq11 <- AAStringSet(seq11)
names(seq11) <- "C_obsidiansis"


seq12 <- getUniProt("A0LTV0")
seq12 <- seq12[[1]]
seq12 <- AAStringSet(seq12)
names(seq12) <- "A_cellulyticus"


seq13 <- getUniProt("Q8TWJ5")
seq13 <- seq13[[1]]
seq13 <- AAStringSet(seq13)
names(seq13) <- "M_kandleri"

seq14 <- getUniProt("P61875")
seq14 <- seq14[[1]]
seq14 <- AAStringSet(seq14)
names(seq14) <- "P_furiosus"


seq15 <- getUniProt("B8D6A9")
seq15 <- seq15[[1]]
seq15 <- AAStringSet(seq15)
names(seq15) <- "D_amyloyticus"

seq16 <- getUniProt("A0A650CS90")
seq16 <- seq16[[1]]
seq16 <- AAStringSet(seq16)
names(seq16) <- "A_ambivalens"

#### end ####



#### set sequences to buried residues only ####

seq1 <- "MMMMMMMMMMQQHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFPPPPESSSSSSSSSSSSSSSSSLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGTTTTTTTTTDDDDDDNNNNNIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKYYYYYYYYYYYYYYYYYYYYYCCCCC"
seq1 <- AAStringSet(seq1)
names(seq1) <- "C_beringensis"


seq2 <- "MMMMMMMMMMMMMMMMMMMMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLDDDDGGGGGGGGGGGGGGGNSSSSSSSSSSSYYYYYYYYYYYYYYYYYYYRRRFFFFFFFFFFFFFFFFFFFFFFFFFFPTTTTTTTTTTTTTTEHHHVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQQQWWC"
seq2 <- AAStringSet(seq2)
names(seq2) <- "P_antarcticus"


seq3 <- "MMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSNNNNNIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLGGGGGGGGGGGGGGGGGGGGYYYYYYYYYYYYYYYYYYYYYYYYYYYYYTTTTTTTTTTTTTTTTEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFPPDDHHHHHHVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVCCCCWWWWWWW"
seq3 <- AAStringSet(seq3)
names(seq3) <- "M_burtonii"

seq4 <- "MMMMMMMMMMMMMMMMMMMMMMEGGGGGGGGGGGGGVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFFFFFFFFFFFFFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLDDDNSSSSSSSSSSSYYYYYYYYYYYYYYYYYRRRTTTTTTTTTTTHHQQQWW"
seq4 <- AAStringSet(seq4)
names(seq4) <- "P_halocryophilus"

seq5 <- "RRRRHHHHHDDDEESSSSSSSSSSTTTTTTTTTTTTTQQCGGGGGGGGGPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYYYYWW"
seq5 <- AAStringSet(seq5)
names(seq5) <- "E_coli"

seq6 <- "RRRHHKEEESSSSSSSSSTTTTTTTTTQCCCCCCCCGGGGGGGGGPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYWWWWWWWWW"
seq6 <- AAStringSet(seq6)
names(seq6) <- "D_thiosulfatigenes"

seq7 <- "RRRHHHHKKKKDDDDEEESSSSSSSSSSSSSTTTTTTTTTTTTQQGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYW"
seq7 <- AAStringSet(seq7)
names(seq7) <- "S_aureus"

seq8 <- "RRHHEESSSSSSSSSSTTTTTTTNQCCCCCCCCCGGGGGGGGGGGGPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYWWWWWWWWWWW"
seq8 <- AAStringSet(seq8)
names(seq8) <- "P_asaccharolyticus"


seq9 <- "RRRRHHHHHDESSSSSSSSSSTTTTTTTTGGGGGGGGGGPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYWWW"
seq9 <- AAStringSet(seq9)
names(seq9) <- "T_aquaticus"


seq10 <- "RRHKKDDESSSSSSTTTTTTTTNNNQQQGGGGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYWW"
seq10 <- AAStringSet(seq10)
names(seq10) <- "G_stearothermophilus"


seq11 <- "RRHDDEEEESSSSSSSSSSSTTTTTTTNNNQCCGGGGGGGGGGGPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMFFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYYYYYYYY"
seq11 <- AAStringSet(seq11)
names(seq11) <- "C_obsidiansis"



seq12 <- "RRRRHHHHDESSSSSSSTTTTTTTTTTTTTTCGGGGGGGGGGGGGGGGPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYWWWWW"
seq12 <- AAStringSet(seq12)
names(seq12) <- "A_cellulyticus"



seq13 <- "RRRRRHHDDEEEESSSSSSSTTTTTTTTTNNNCCCCGGGGGGGGGPPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYYYYYYYWWWWWWWW"
seq13 <- AAStringSet(seq13)
names(seq13) <- "M_kandleri"


seq14 <- "HHHDDESSSSSSSSTTTTTTTNCCGGGGGGGGGPPPAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYWWWWWWWWW"
seq14 <- AAStringSet(seq14)
names(seq14) <- "P_furiosus"



seq15 <- "RRHHHKKKKDDDSSSSSSSSSSTTTTTTTTTTTTTTNNNNNQQCCCGGGGGGGGGGPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYYYYYYYYYYYYYYWWWWWW"
seq15 <- AAStringSet(seq15)
names(seq15) <- "D_amyloyticus"


seq16 <- "RRRHKKDDSSSSSSSSSSTTTTTTTTTTTTTTTTNNNNNCCGGGGGGGGGGPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMMMFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYWWWWWWW"
seq16 <- AAStringSet(seq16)
names(seq16) <- "A_ambivalens"

#### end ####



#### set sequences to exposed residues only ####


seq1 <- "MMMMMQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQHHHHHHHHHHHHHFFFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLLLLLLLLLLLLLLLLLLLLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRTTTTTTTTTTTTTTTTTTTTTTTTTTTDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNIIIIIIIIIIWWVVVVVVVVVVVVVVKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKYYYYYYYYYYYYCC"
  seq1 <- AAStringSet(seq1)
names(seq1) <- "C_beringensis"


seq2 <- "MMMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKIIIIIIIIIILLLLLLLLLLLLLLLLLLLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGNNNNNNNNNNNNNNNNNNNNNNNNNNNNSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSYYYYYYYYYYYYYYYRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEHHHHHHHHHHHHHHHVVVVVVVVVVVVVVVVQQQQQQQQQQQQQQQQQQQQQQQQQQWWW"
  seq2 <- AAStringSet(seq2)
names(seq2) <- "P_antarcticus"


seq3 <- "MMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNIIIIIIIIIIIIIIIIAAAAAAAAAAAAAAALLLLLLLLLLLRRRRRRRRRRRRRRRRRRRRRRRRRRGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGYYYYYYYYYYYYYYYYTTTTTTTTTTTTTTTTTTTTTTTTTTTTQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDHHHHHHHHHHHHHVVVVVVC"
  seq3 <- AAStringSet(seq3)
names(seq3) <- "M_burtonii"

seq4 <- "MMMMMMMEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGVVVVVVVVVVVVVVVVVVIIIIIIIIIIFFFFFFAAAAAAAAAAAAAAAAAAAAAAAAAAAKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLLLLLLLLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSYYYYYYYYYYYYYYYRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTHHHHHHHHHHHHHHHHHHHQQQQQQQQQQQQQQQQQQQQQQQQQQQQQWWWC"
  seq4 <- AAStringSet(seq4)
names(seq4) <- "P_halocryophilus"

seq5 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMMMFYYYYYYYYYYYYYWWWWW"
  seq5 <- AAStringSet(seq5)
names(seq5) <- "E_coli"

seq6 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQQQCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVIIIIIIIIIIILLLLLLLLMMMMMFFFFYYYYYYWW"
  seq6 <- AAStringSet(seq6)
names(seq6) <- "D_thiosulfatigenes"

seq7 <- "RRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIIIIIIILLLLLLLLLLLLLLMMMFFFFFFFYYYYYYYYYYYYYYYYYYYYYYW"
  seq7 <- AAStringSet(seq7)
names(seq7) <- "S_aureus"

seq8 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAVVVVVVVVVVIIILLLLLLLLLLLMMMMMMMMFFFFFYYYYYYYYWWW"
  seq8 <- AAStringSet(seq8)
names(seq8) <- "P_asaccharolyticus"


seq9 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNQQQQQQQQQQQQQQQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMFFFFFYYYYYYYYYYWWWWWWWWWWW"
  seq9 <- AAStringSet(seq9)
names(seq9) <- "T_aquaticus"


seq10 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVIIIIIIIILLLLLLLLLLLLLLLLLLLMMMMMMMMFFFYYYYYYYYYYYYWWW"
  seq10 <- AAStringSet(seq10)
names(seq10) <- "G_stearothermophilus"


seq11 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQCCCGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAVVVVVVVVVVVVVIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLMMMMMMFFFFFFFYYYYYYYYYYYYYYYYYYYYYWWWWW"
  seq11 <- AAStringSet(seq11)
names(seq11) <- "C_obsidiansis"



seq12 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVIIIIILLLLLLLLLLLLLLLLLMMFFFYYYYYYYYWWWW"
  seq12 <- AAStringSet(seq12)
names(seq12) <- "A_cellulyticus"



seq13 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNQQQQQQQQQQQQQQCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVVVVIIIIIIIIIILLLLLLLLLLLLLLLLLLMFFFFFFFFFYYYYYYYYYYYYYYYYW"
  seq13 <- AAStringSet(seq13)
names(seq13) <- "M_kandleri"


seq14 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAAAAVVVVVVVVVVVIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLMMMMMMFFFFFYYYYYYYYYYYYYYYWW"
  seq14 <- AAStringSet(seq14)
names(seq14) <- "P_furiosus"



seq15 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAAAAAAAVVVVVVVVVVVVIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLMMMMMMMMMFFFFFYYYYYYYYYYYYYYWWWW"
  seq15 <- AAStringSet(seq15)
names(seq15) <- "D_amyloyticus"


seq16 <- "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRHHHHHHHHHKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNNNNNNNNNNNNNNNNQQQQQQQQQQQQQQQQQQQQQQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPAAAAAAAAAAAAVVVVVVVVVVVVVVVVIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLMMMMMMMFFFFFFYYYYYYYYYYYYWWW"
  seq16 <- AAStringSet(seq16)
names(seq16) <- "A_ambivalens"


#### end ####



#### Make individual dataframe ####

sequences <- c(seq1, seq2, seq3, seq4, seq5, seq6, seq7, seq8, seq9, seq10, seq11, seq12, seq13, seq14, seq15, seq16)
sequences <- AAStringSet(sequences)

optimalTemps <- c(12, 20, 21, 25, 37, 30, 37, 37, 70, 60, 78, 55, 97, 96, 90, 80)

tempCategories <- c("p", "p", "p", "p", "m", "m", "m", "m", "t", "t", "t", "t", "h", "h", "h", "h")

names <- c("C_beringensis", "P_antarcticus", "M_burtonii", "P_halocryophilus",  
           "E_coli", "D_thiosulfatigenes", "S_aureus", "P_asaccharolyticus", 
           "T_aquaticus", "G_stearothermophilus", "C_obsidiansis", "A_cellulyticus", 
           "M_kandleri", "P_furiosus", "D_amyloyticus", "A_ambivalens")

indFrame = data.frame(names, tempCategories, optimalTemps, sequences)
indFrame[, "Length"] <- NA
for (i in seq(from=1, to=16, by=1)){
  seqToRead <- indFrame$sequences[[i]]
  lengthToAdd <- width(seqToRead[1])
  indFrame$Length[[i]] <- lengthToAdd
}


#### end ####



#### Perform MSA (all commented out)####

 multifasta <- Biostrings::AAStringSet(unlist(Proteins_IDs))

fastaPath <- paste(folderPath, "/polSeqs.fasta", sep="")
Biostrings::writeXStringSet(sequences, fastaPath)


#MSalignment <- muscle(sequences, quiet=FALSE)

#align2 <- AAStringSet(MSalignment)

#alignPath <- paste(folderPath, "/MSalignment.fasta", sep="")
#Biostrings::writeXStringSet(align2, file = alignPath, format="fasta")

#### end ####



#### Calculate AA frequencies and add to individual frame. Calculated averages/SDs for each group and make group frame####
AACodes <- c("R", "H", "K", "D", "E", "S", "T", "N", "Q", "C", "G", "P", "A", "V", "I", 
             "L", "M", "F", "Y", "W")

for (i in AACodes){
  indFrame[, i] <- 0
}

for (i in AACodes){
  for (j in seq(from=1, to=16, by=1)){
    toAdd <- str_count(indFrame$sequences[[j]], i)
    toAdd <- toAdd/indFrame$Length[[j]]
  indFrame[[i]][[j]] <- toAdd
  }
}

singleCats <- c("psychrophile", "mesophile", "thermophile", "hyperthermophile")
groupFrame <- data.frame(singleCats)
  
for (i in AACodes){
  groupFrame[, i] <- 0
  stDevName <- paste(i, " stdev")
}

for (i in AACodes){
  
  stDevName <- paste(i, " stdev")
  groupFrame[[i]][[1]] <- mean(indFrame[[i]][1:4])
  groupFrame[[i]][[2]] <- mean(indFrame[[i]][5:8])
  groupFrame[[i]][[3]] <- mean(indFrame[[i]][9:12])
  groupFrame[[i]][[4]] <- mean(indFrame[[i]][13:16])
  
  groupFrame[[stDevName]][[1]] <- sd(indFrame[[i]][1:4])
  groupFrame[[stDevName]][[2]] <- sd(indFrame[[i]][5:8])
  groupFrame[[stDevName]][[3]] <- sd(indFrame[[i]][9:12])
  groupFrame[[stDevName]][[4]] <- sd(indFrame[[i]][13:16])
}


#### end ####





#### T tests comparing the groups####
comparison <- c("Psychro/Meso", "Psychro/Thermo", "Psychro/Hyper", "Meso/Thermo", "Meso/Hyper", "Thermo/Hyper")
tFrame <- data.frame(comparison)
for (i in AACodes){
  tFrame[, i] <- 0
}


for (i in AACodes){

  # Psychro/Meso
  tFrame[[i]][[1]] <- t.test(indFrame[[i]][1:4], indFrame[[i]][5:8])$p.value

  
  # Psychro/Thermo
  tFrame[[i]][[2]] <- t.test(indFrame[[i]][1:4], indFrame[[i]][9:12])$p.value
  
  # Psychro/Hyper
  tFrame[[i]][[3]] <- t.test(indFrame[[i]][1:4], indFrame[[i]][13:16])$p.value
  
  # Meso/Thermo
  tFrame[[i]][[4]] <- t.test(indFrame[[i]][5:8], indFrame[[i]][9:12])$p.value
  
  # Meso/Hyper
  tFrame[[i]][[5]] <- t.test(indFrame[[i]][5:8], indFrame[[i]][13:16])$p.value
  
  # Thermo/Hyper
  tFrame[[i]][[6]] <- t.test(indFrame[[i]][9:12], indFrame[[i]][13:16])$p.value
}

#### end ####

dev.off()



